# Generated by Django 5.2.12 on 2026-05-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.AlterField(
            model_name='property',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='NGN', max_length=10),
        ),
    ]
