# Generated by Codex on 2026-05-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add optional locations to agent and client profiles."""

    dependencies = [
        ('estate', '0002_remove_client_email_alter_property_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='location',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='agents',
                to='estate.location',
            ),
        ),
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='clients',
                to='estate.location',
            ),
        ),
    ]
