# Generated by Codex on 2026-05-02

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add optional company field to client profiles."""

    dependencies = [
        ('estate', '0003_agent_location_client_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
