# Generated by Django 5.2.12 on 2026-05-04 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_client_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription',
            field=models.CharField(choices=[('F', 'Free'), ('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold')], default='F', max_length=1),
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=255)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.subscription')),
            ],
        ),
    ]
