from django.urls import path
from .views import (
    AgentDetailView,
    AgentListCreateView,
    ClientDetailView,
    ClientListCreateView,
    FavoriteDetailView,
    FavoriteListCreateView,
    LocationDetailView,
    LocationListCreateView,
    PropertyDetailView,
    PropertyFeatureDetailView,
    PropertyFeatureListCreateView,
    PropertyImageDetailView,
    PropertyImageListCreateView,
    PropertyListCreateView,
    SubscriptionDetailView,
    SubscriptionListCreateView,
)

app_name = "estate"

urlpatterns = [
    path("location", LocationListCreateView.as_view(),
         name="location-list-create"),
    path("location/<int:pk>/", LocationDetailView.as_view(), name="location-detail"),
    path("agent", AgentListCreateView.as_view(), name="agent-list-create"),
    path("agent/<int:pk>/", AgentDetailView.as_view(), name="agent-detail"),
    path("client", ClientListCreateView.as_view(), name="client-list-create"),
    path("client/<int:pk>/", ClientDetailView.as_view(), name="client-detail"),
    path("property", PropertyListCreateView.as_view(),
         name="property-list-create"),
    path("property/<int:pk>/", PropertyDetailView.as_view(), name="property-detail"),
    path("property-image", PropertyImageListCreateView.as_view(),
         name="property-image-list-create"),
    path("property-image/<int:pk>/", PropertyImageDetailView.as_view(),
         name="property-image-detail"),
    path("property-features", PropertyFeatureListCreateView.as_view(),
         name="property-features-list-create"),
    path("property-features/<int:pk>/",
         PropertyFeatureDetailView.as_view(), name="property-features-detail"),
    path("favorites", FavoriteListCreateView.as_view(),
         name="favorites-list-create"),
    path("favorites/<int:pk>/", FavoriteDetailView.as_view(),
         name="favorites-detail"),
    path("subscription", SubscriptionListCreateView.as_view(),
         name="subscription-list-create"),
    path("subscription/<int:pk>/", SubscriptionDetailView.as_view(),
         name="subscription-detail"),
]


# urlpatterns = [
#     path('', views.index, name='index'),
#     path('properties/', views.property_list, name='property_list'),
#     path('properties/<int:property_id>/',
#          views.property_detail, name='property_detail'),
#     path('agents/', views.agent_list, name='agent_list'),
#     path('agents/<int:agent_id>/', views.agent_detail, name='agent_detail'),
#     path('clients/', views.client_list, name='client_list'),
#     path('clients/<int:client_id>/', views.client_detail, name='client_detail'),
#     path('locations/', views.location_list, name='location_list'),
#     path('locations/<int:location_id>/',
#          views.location_detail, name='location_detail'),
#     path('subscriptions/', views.subscription_list, name='subscription_list'),
#     path('subscriptions/<int:subscription_id>/',
#          views.subscription_detail, name='subscription_detail'),
#     path('property_features/', views.property_feature_list,
#          name='property_feature_list'),
#     path('property_features/<int:feature_id>/',
#          views.property_feature_detail, name='property_feature_detail'),
#     path('property_images/', views.property_image_list,
#          name='property_image_list'),
#     path('property_images/<int:image_id>/',
#          views.property_image_detail, name='property_image_detail'),
#     path('favorites/', views.favorite_list, name='favorite_list'),
# ]
